main = {
"version": 0.1,
"ClassType": {
    "mod": {"name": "Name", "displayName": "DisplayName", "description": "Description", "author": "Author",
            "version": "0.1", "minGameVersion": "105", "dependencies": [], "hidden": False},

    "UnlockableContent": {"name": "Name", "localizedName": "Local Name", "description": "Description", "fullIcon": None,
                          "generateIcons": True, "hideDetails": False, "iconId": -1, "inlineDescription": True,
                          "alwaysUnlocked": True},

    "Block": {"extend": "UnlockableContent", "hasItems": False, "hasLiquids": False, "hasPower": False,
              "outputsLiquid": False, "consumesPower": True, "outputsPower": False, "conductivePower": False,
              "outputsPayload": False, "acceptsPayload": False, "acceptsItems": False, "separateItemCapacity": False,
              "itemCapacity": 10, "liquidCapacity": 10.0, "liquidPressure": 1.0, "outputFacing": True,
              "noSideBlend": False, "displayFlow": True, "inEditor": True, "lastConfig": None, "saveConfig": False,
              "copyConfig": True, "clearOnDoubleTap": False, "update": False, "destructible": False, "unloadable": True,
              "isDuct": False, "allowResupply": False, "solid": False, "solidifes": False, "teamPassable": False,
              "underBullets": False, "rotate": False, "rotateDraw": True, "invertFlip": False, "variants": 0,
              "drawArrow": True, "drawTeamOverlay": True, "saveData": False, "breakable": False, "rebuildable": True,
              "privileged": False, "requiresWater": False, "placeableLiquid": False, "placeablePlayer": True,
              "placeableOn": True, "insulated": False, "squareSprite": True, "absorbLasers": False,
              "enableDrawStatus": True, "drawDisabled": True, "autoResetEnabled": True, "noUpdateDisabled": False,
              "updateInUnits": True, "alwaysUpdateInUnits": False, "useColor": True, "itemDrop": None,
              "playerUnmineable": False, "attributes": None, "scaledHealth": -1.0, "health": -1, "armor": 0.0,
              "baseExplosiveness": 0.0, "destroyBullet": None, "drawCracks": True, "createRubble": True,
              "floating": False, "size": 1, "offset": 0.0, "sizeOffset": 0, "clipSize": -1.0, "placeOverlapRange": 50.0,
              "crushDamageMultiplier": 1.0, "timers": 1, "cacheLayer": "normal", "fillsTile": True, "forceDark": False,
              "alwaysReplace": False, "replaceable": True, "group": None, "flags": "of()", "priority": 0.0,
              "unitCapModifier": 0, "configurable": False, "commandable": False, "allowConfigInventory": True,
              "logicConfigurable": False, "consumesTap": False, "drawLiquidLight": True, "envRequired": 0,
              "envEnabled": 1, "envDisabled": 0, "sync": False, "conveyorPlacement": False, "allowDiagonal": True,
              "swapDiagonalPlacement": False, "schematicPriority": 0, "mapColor": "000000ff", "hasColor": False,
              "targetable": True, "attacks": False, "suppressable": False, "canOverdrive": True,
              "outlineColor": "404049ff", "outlineIcon": False, "outlineRadius": 4, "outlinedIcon": -1,
              "hasShadow": True, "customShadow": False, "placePitchChange": True, "breakPitchChange": True,
              "placeSound": "place", "breakSound": "breaks", "destroySound": "boom", "albedo": 0.0,
              "lightColor": "ffffffff", "emitLight": False, "lightRadius": 60.0, "fogRadius": -1, "loopSound": None,
              "loopSoundVolume": 0.5, "ambientSound": None, "ambientSoundVolume": 0.05, "requirements": [],
              "category": "distribution", "buildCost": 20.0, "buildVisibility": "hidden", "buildCostMultiplier": 1.0,
              "deconstructThreshold": 0.0, "instantDeconstruct": False, "breakEffect": "breakBlock",
              "destroyEffect": "dynamicExplosion", "researchCostMultiplier": 1.0, "researchCostMultipliers": None,
              "researchCost": None, "instantTransfer": False, "quickRotate": True, "subclass": None,
              "highUnloadPriority": False, "selectScroll": 0.0, "buildType": None, "configurations": None,
              "itemFilter": [], "liquidFilter": [], "consumers": [], "optionalConsumers": [],
              "nonOptionalConsumers": [], "updateConsumers": [], "hasConsumers": False, "consPower": None,
              "regionRotated1": -1, "regionRotated2": -1, "region": None, "editorIcon": None,
              "customShadowRegion": None, "teamRegion": None, "teamRegions": None, "variantRegions": None,
              "variantShadowRegions": None},

    "Accelerator": {"extend": "Block", "arrowRegion": None, "launching": "coreNucleus", "capacities": []},
    "Floor": {"extend": "Block", "edge": "stone", "speedMultiplier": 1.0, "dragMultiplier": 1.0, "damageTaken": 0.0,
              "drownTime": 0.0, "walkEffect": None, "walkSound": None, "walkSoundVolume": 0.1, "walkSoundPitchMin": 0.8,
              "walkSoundPitchMax": 1.2, "drownUpdateEffect": "bubble", "status": None, "statusDuration": 60.0,
              "liquidDrop": None, "liquidMultiplier": 1.0, "isLiquid": False, "overlayAlpha": 0.65,
              "supportsOverlay": False, "shallow": False, "blendGroup": "this", "oreDefault": False, "oreScale": 24.0,
              "oreThreshold": 0.828, "wall": "air", "decoration": "air", "canShadow": True, "needsSurface": True,
              "allowCorePlacement": False, "wallOre": False, "blendId": -1},
    "AirBlock": {"extend": "Floor"},
    "EmptyFloor": {"extend": "Floor"},
    "ShallowLiquid": {"extend": "Floor", "liquidBase": None, "floorBase": None, "liquidOpacity": 0.35},
    "OverlayFloor": {"extend": "Floor"},
    "OreBlock": {"extend": "OverlayFloor"},
    "LiquidBlock": {"extend": "Block", "liquidRegion": None, "topRegion": None, "bottomRegion": None},
    "LiquidJunction": {"extend": "LiquidBlock"},
    "LiquidRouter": {"extend": "LiquidBlock", "liquidPadding": 0.0},

    "Pump": {"extend": "LiquidBlock", "pumpAmount": 0.2, "consumeTime": 300.0, "drawer": None},
    "SolidPump": {"extend": "Pump", "result": "water", "updateEffect": None, "updateEffectChance": 0.02,
                  "rotateSpeed": 1.0, "baseEfficiency": 1.0, "attribute": None, "rotatorRegion": None},
    "Fracker": {"extend": "SolidPump", "itemUseTime": 100.0},
    "Conduit": {"extend": "LiquidBlock", "timerFlow": 1, "botColor": "565656ff", "topRegions": None, "botRegions": None,
                "capRegion": None, "rotateRegions": None, "leaks": True, "junctionReplacement": None,
                "bridgeReplacement": None, "rotBridgeReplacement": None},
    "ArmoredConduit": {"extend": "Conduit"},
    "Conveyor": {"extend": "Block", "regions": None, "speed": 0.0, "displayedSpeed": 0.0, "junctionReplacement": None,
                 "bridgeReplacement": None},
    "ArmoredConveyor": {"extend": "Conveyor"},
    "GenericCrafter": {"extend": "Block", "outputItem": None, "outputItems": None, "outputLiquid": None,
                       "outputLiquids": None, "liquidOutputDirections": [-1], "dumpExtraLiquid": True,
                       "ignoreLiquidFullness": False, "craftTime": 80.0, "craftEffect": None, "updateEffect": None,
                       "updateEffectChance": 0.04, "warmupSpeed": 0.019, "legacyReadWarmup": False, "drawer": None},
    "AttributeCrafter": {"extend": "GenericCrafter", "attribute": "heat", "baseEfficiency": 1.0, "boostScale": 1.0,
                         "maxBoost": 1.0, "minEfficiency": -1.0, "displayEfficiencyScale": 1.0,
                         "displayEfficiency": True},
    "HeatCrafter": {"extend": "GenericCrafter", "heatRequirement": 10.0, "overheatScale": 1.0, "maxEfficiency": 4.0},
    "HeatProducer": {"extend": "GenericCrafter", "heatOutput": 10.0, "warmupRate": 0.15},
    "Wall": {"extend": "Block", "lightningChance": -1.0, "lightningDamage": 20.0, "lightningLength": 17,
             "lightningColor": "f3e979ff", "lightningSound": "spark", "chanceDeflect": -1.0, "flashHit": False,
             "flashColor": "ffffffff", "deflectSound": None},
    "AutoDoor": {"extend": "Wall", "timerToggle": 1, "checkInterval": 20.0, "openfx": "dooropen",
                 "closefx": "doorclose", "doorSound": "door", "openRegion": None, "triggerMargin": 12.0},
    "BaseShield": {"extend": "Wall", "radius": 200.0, "sides": 24},
    "Door": {"extend": "Wall", "timerToggle": 1, "openfx": "dooropen", "closefx": "doorclose", "doorSound": "door",
             "openRegion": None},
    "BaseTurret": {"extend": "Block", "range": 80.0, "placeOverlapMargin": 56.0, "rotateSpeed": 5.0,
                   "coolEffect": "fuelburn", "coolantMultiplier": 5.0, "coolant": None},
    "BuildTurret": {"extend": "BaseTurret", "timerTarget": 1, "timerTarget2": 2, "targetInterval": 15,
                    "baseRegion": None, "glowRegion": None, "buildSpeed": 1.0, "buildBeamOffset": 5.0, "unitType": None,
                    "elevation": -1.0, "heatColor": "ffd37fe5"},
    "StorageBlock": {"extend": "Block", "coreMerge": True},
    "CoreBlock": {"extend": "StorageBlock", "thruster1": None, "thruster2": None, "thrusterLength": 3.5,
                  "isFirstTier": False, "incinerateNonBuildable": False, "unitType": "alpha",
                  "captureInvicibility": 900.0},
    "Drill": {"extend": "Block", "hardnessDrillMultiplier": 50.0, "tier": 0, "drillTime": 300.0,
              "liquidBoostIntensity": 1.6, "warmupSpeed": 0.015, "blockedItem": None, "drawMineItem": True,
              "drillEffect": "mine", "drillEffectRnd": -1.0, "rotateSpeed": 2.0, "updateEffect": "pulverizeSmall",
              "updateEffectChance": 0.02, "drawRim": False, "drawSpinSprite": True, "heatColor": "ff5512ff",
              "rimRegion": None, "rotatorRegion": None, "topRegion": None, "itemRegion": None},
    "BurstDrill": {"extend": "Drill", "shake": 2.0, "speedCurve": "pow2In", "topInvertRegion": None, "glowRegion": None,
                   "arrowRegion": None, "arrowBlurRegion": None, "invertedTime": 200.0, "arrowSpacing": 4.0,
                   "arrowOffset": 0.0, "arrows": 3, "arrowColor": "feb380ff", "baseArrowColor": "6e7080ff",
                   "glowColor": "feb380ff"},
    "DroneCenter": {"extend": "Block", "unitsSpawned": 4, "droneType": None, "status": "overdrive",
                    "droneConstructTime": 180.0, "statusDuration": 120.0, "droneRange": 50.0},
    "HeatConductor": {"extend": "Block", "visualMaxHeat": 15.0, "drawer": None},
    "Junction": {"extend": "Block", "speed": 26.0, "capacity": 6},
    "ItemBridge": {"extend": "Block", "timerCheckMoved": 1, "range": 0, "transportTime": 2.0, "endRegion": None,
                   "bridgeRegion": None, "arrowRegion": None, "fadeIn": True, "moveArrows": True, "pulse": False,
                   "arrowSpacing": 4.0, "arrowOffset": 2.0, "arrowPeriod": 0.4, "arrowTimeScl": 6.2, "lastBuild": None},
    "LiquidBridge": {"extend": "ItemBridge"},
    "BufferedItemBridge": {"extend": "ItemBridge", "timerAccept": 2, "speed": 40.0, "bufferCapacity": 50},
    "LiquidVoid": {"extend": "Block"},
    "MassDriver": {"extend": "Block", "range": 0.0, "rotateSpeed": 5.0, "translation": 7.0, "minDistribute": 10,
                   "knockback": 4.0, "reload": 100.0, "bullet": None, "bulletSpeed": 5.5, "bulletLifetime": 200.0,
                   "shootEffect": "shootBig2", "smokeEffect": "shootBigSmoke2", "receiveEffect": "mineBig",
                   "shootSound": "shootBig", "shake": 3.0, "baseRegion": None},
    "MemoryBlock": {"extend": "Block", "memoryCapacity": 32},
    "MendProjector": {"extend": "Block", "timerUse": 1, "baseColor": "84f491ff", "phaseColor": "84f491ff",
                      "topRegion": None, "reload": 250.0, "range": 60.0, "healPercent": 12.0, "phaseBoost": 12.0,
                      "phaseRangeBoost": 50.0, "useTime": 400.0},
    "PayloadBlock": {"extend": "Block", "payloadSpeed": 0.7, "payloadRotateSpeed": 5.0, "regionSuffix": "",
                     "topRegion": None, "outRegion": None, "inRegion": None},
    "PayloadMassDriver": {"extend": "PayloadBlock", "range": 100.0, "rotateSpeed": 2.0, "length": 11.125,
                          "knockback": 5.0, "reload": 30.0, "chargeTime": 100.0, "maxPayloadSize": 3.0,
                          "grabWidth": 8.0, "grabHeight": 2.75, "shootEffect": "shootBig2",
                          "smokeEffect": "shootPayloadDriver", "receiveEffect": "payloadReceive",
                          "shootSound": "shootBig", "shake": 3.0, "transferEffect": "flyingUnitLow - 1)",
                          "baseRegion": None, "capRegion": None, "leftRegion": None, "rightRegion": None,
                          "capOutlineRegion": None, "leftOutlineRegion": None, "rightOutlineRegion": None,
                          "arrow": None},
    "PayloadVoid": {"extend": "PayloadBlock", "incinerateEffect": "blastExplosion", "incinerateSound": "bang"},
    "PayloadSource": {"extend": "PayloadBlock"},
    "UnitBlock": {"extend": "PayloadBlock"},
    "Reconstructor": {"extend": "UnitBlock", "constructTime": 120.0, "upgrades": None, "capacities": []},
    "PowerBlock": {"extend": "Block"},
    "PayloadDeconstructor": {"extend": "PowerBlock", "maxPayloadSize": 4.0, "deconstructSpeed": 2.5, "dumpRate": 4},
    "PayloadLoader": {"extend": "PowerBlock", "timerLoad": 1, "loadTime": 2.0, "itemsLoaded": 8, "liquidsLoaded": 40.0,
                      "maxBlockSize": 3, "maxPowerConsumption": 40.0, "loadPowerDynamic": True},
    "PayloadUnloader": {"extend": "PayloadLoader", "offloadSpeed": 4, "maxPowerUnload": 80.0},
    "PowerNode": {"extend": "PowerBlock", "laser": None, "laserEnd": None, "laserRange": 6.0, "maxNodes": 3,
                  "autolink": True, "drawRange": True, "laserScale": 0.25, "laserColor1": "ffffffff",
                  "laserColor2": "fbd367ff"},
    "LongPowerNode": {"extend": "PowerNode", "glow": None, "glowColor": "cbfd8172", "glowScl": 16.0, "glowMag": 0.6},
    "PowerSource": {"extend": "PowerNode", "powerProduction": 10000.0},
    "PowerVoid": {"extend": "PowerBlock"},
    "PowerDistributor": {"extend": "PowerBlock"},
    "Battery": {"extend": "PowerDistributor", "topRegion": None, "emptyLightColor": "f8c266ff",
                "fullLightColor": "fb9567ff"},
    "PowerGenerator": {"extend": "PowerDistributor", "powerProduction": 0.0, "generationType": "basePowerGeneration",
                       "drawer": None},
    "ConsumeGenerator": {"extend": "PowerGenerator", "itemDuration": 120.0, "effectChance": 0.01,
                         "generateEffect": None, "consumeEffect": None, "generateEffectRange": 3.0,
                         "liquidOutput": None, "filterItem": None, "filterLiquid": None},
    "ImpactReactor": {"extend": "PowerGenerator", "timerUse": 1, "warmupSpeed": 0.001, "itemDuration": 60.0,
                      "explosionRadius": 23, "explosionDamage": 1900, "explodeEffect": "impactReactorExplosion",
                      "plasma1": "ffd06bff", "plasma2": "ff361bff", "bottomRegion": None, "plasmaRegions": None},
    "NuclearReactor": {"extend": "PowerGenerator", "timerFuel": 1, "tr": None, "lightColor": "7f19eaff",
                       "coolColor": "ffffff00", "hotColor": "ff9575a3", "explodeEffect": "reactorExplosion",
                       "itemDuration": 120.0, "heating": 0.01, "smokeThreshold": 0.3, "flashThreshold": 0.46,
                       "explosionRadius": 19, "explosionDamage": 1250, "coolantPower": 0.5, "smoothLight": 0.0,
                       "fuelItem": "thorium", "topRegion": None, "lightsRegion": None},
    "BeamNode": {"extend": "PowerBlock", "range": 5, "laser": None, "laserEnd": None, "laserColor1": "ffffffff",
                 "laserColor2": "ffd9c2ff", "pulseScl": 7.0, "pulseMag": 0.05, "laserWidth": 0.4},
    "BeamDrill": {"extend": "Block", "laser": None, "laserEnd": None, "laserCenter": None, "laserBoost": None,
                  "laserEndBoost": None, "laserCenterBoost": None, "topRegion": None, "glowRegion": None,
                  "drillTime": 200.0, "range": 5, "tier": 1, "laserWidth": 0.65, "optionalBoostIntensity": 2.5,
                  "sparkColor": "fd9e81ff", "glowColor": "ffffffff", "glowIntensity": 0.2, "pulseIntensity": 0.07,
                  "glowScl": 3.0, "sparks": 7, "sparkRange": 10.0, "sparkLife": 27.0, "sparkRecurrence": 4.0,
                  "sparkSpread": 45.0, "sparkSize": 3.5, "boostHeatColor": "75b3ccff", "heatColor": "ff5959e5",
                  "heatPulse": 0.3, "heatPulseScl": 7.0},
    "CanvasBlock": {"extend": "Block", "padding": 0.0, "canvasSize": 8,
                    "palette": [0x634b7dff, 0xc45d9f_ff, 0xe39aac_ff, 0xf0dab1_ff, 0x6461c2_ff, 0x2ba9b4_ff,
                                0x93d4b5_ff, 0xf0f6e8_ff], "bitsPerPixel": 0, "colorToIndex": None},
    "Cliff": {"extend": "Block", "size": 11.0, "cliffs": None, "editorCliffs": None},

    "BaseTurret": {"extend": "Block", "range": 80.0, "placeOverlapMargin": 56.0, "rotateSpeed": 5.0,
                   "coolEffect": "fuelburn", "coolantMultiplier": 5.0, "coolant": None},
    "ReloadTurret": {"extend": "BaseTurret", "reload": 10.0},
    "PointDefenseTurret": {"extend": "ReloadTurret", "timerTarget": 1, "retargetTime": 5.0, "baseRegion": None,
                           "color": "ffffffff", "beamEffect": "pointBeam", "hitEffect": "pointHit",
                           "shootEffect": "sparkShoot", "shootSound": "lasershoot", "shootCone": 5.0,
                           "bulletDamage": 10.0, "shootLength": 3.0},
    "Turret": {"extend": "ReloadTurret", "timerTarget": 1, "targetInterval": 20.0, "maxAmmo": 30, "ammoPerShot": 1,
               "consumeAmmoOnce": True, "heatRequirement": -1.0, "maxHeatEfficiency": 3.0, "inaccuracy": 0.0,
               "velocityRnd": 0.0, "shootCone": 8.0, "shootX": 0.0, "shootY": None, "xRand": None, "minRange": 0.0,
               "minWarmup": 0.0, "accurateDelay": True, "moveWhileCharging": True, "shoot": None, "targetAir": True,
               "targetGround": True, "targetHealing": False, "playerControllable": True, "displayAmmoMultiplier": True,
               "unitSort": "closest", "unitFilter": ["code"], "buildingFilter": "underBullets", "heatColor": "ab3400ff",
               "shootEffect": None, "smokeEffect": None, "ammoUseEffect": None, "shootSound": "shoot",
               "chargeSound": None, "soundPitchMin": 0.9, "soundPitchMax": 1.1, "ammoEjectBack": 1.0,
               "shootWarmupSpeed": 0.1, "linearWarmup": False, "recoil": 1.0, "recoilTime": -1.0, "recoilPow": 1.8,
               "cooldownTime": 20.0, "elevation": -1.0, "shake": 0.0, "drawer": None},
    "PayloadAmmoTurret": {"extend": "Turret", "ammoTypes": None},
    "ContinuousTurret": {"extend": "Turret", "shootType": "placeholder"},
    "ContinuousLiquidTurret": {"extend": "ContinuousTurret", "ammoTypes": None, "liquidConsumed": 0.016666668},
    "ItemTurret": {"extend": "Turret", "ammoTypes": None},
    "LiquidTurret": {"extend": "Turret", "ammoTypes": None, "extinguish": True},
    "PowerTurret": {"extend": "Turret", "shootType": None},
    "LaserTurret": {"extend": "PowerTurret", "firingMoveFract": 0.25, "shootDuration": 100.0},
    "DirectionBridge": {"extend": "Block", "bridgeRegion": None, "bridgeBotRegion": None, "bridgeLiquidRegion": None,
                        "arrowRegion": None, "dirRegion": None, "range": 4},
    "DirectionLiquidBridge": {"extend": "DirectionBridge", "timerFlow": 1, "speed": 5.0, "liquidPadding": 1.0,
                              "bottomRegion": None},
    "DuctBridge": {"extend": "DirectionBridge", "speed": 5.0},
    "DirectionalForceProjector": {"extend": "Block", "width": 30.0, "shieldHealth": 3000.0, "cooldownNormal": 1.75,
                                  "cooldownLiquid": 1.5, "cooldownBrokenBase": 0.35, "absorbEffect": "absorb",
                                  "shieldBreakEffect": "shieldBreak", "topRegion": None, "length": 40.0,
                                  "padSize": 40.0},
    "DirectionalUnloader": {"extend": "Block", "centerRegion": None, "topRegion": None, "arrowRegion": None,
                            "speed": 1.0, "allowCoreUnload": False},

    "Duct": {"extend": "Block", "speed": 5.0, "armored": False, "transparentColor": "66666619", "topRegions": None,
             "botRegions": None},
    "DuctRouter": {"extend": "Block", "speed": 5.0, "topRegion": None},

    "ForceProjector": {"extend": "Block", "timerUse": 1, "phaseUseTime": 350.0, "phaseRadiusBoost": 80.0,
                       "phaseShieldBoost": 400.0, "radius": 101.7, "shieldHealth": 700.0, "cooldownNormal": 1.75,
                       "cooldownLiquid": 1.5, "cooldownBrokenBase": 0.35, "coolantConsumption": 0.1,
                       "consumeCoolant": True, "absorbEffect": "absorb", "shieldBreakEffect": "shieldBreak",
                       "topRegion": None, "itemConsumer": None, "coolantConsumer": None},

    "Incinerator": {"extend": "Block", "effect": "fuelburn", "flameColor": "ffad9dff"},
    "ItemIncinerator": {"extend": "Block", "effect": "incinerateSlag", "effectChance": 0.2, "liquidRegion": None,
                        "topRegion": None},
    "ItemSource": {"extend": "Block", "itemsPerSecond": 100},
    "ItemVoid": {"extend": "Block"},
    "LaunchPad": {"extend": "Block", "launchTime": 1.0, "launchSound": None, "lightRegion": None, "podRegion": None,
                  "lightColor": "eab678ff"},

    "LightBlock": {"extend": "Block", "brightness": 0.9, "radius": 200.0, "topRegion": None},

    "LiquidSource": {"extend": "Block", "crossRegion": None, "bottomRegion": None},
    "LogicBlock": {"extend": "Block", "maxInstructionScale": 5, "instructionsPerTick": 1, "maxInstructionsPerTick": 40,
                   "range": 80.0},
    "LogicDisplay": {"extend": "Block", "maxSides": 25, "displaySize": 64, "scaleFactor": 1.0},
    "MessageBlock": {"extend": "Block", "maxTextLength": 220, "maxNewlines": 24},

    "OverdriveProjector": {"extend": "Block", "timerUse": 1, "topRegion": None, "reload": 60.0, "range": 80.0,
                           "speedBoost": 1.5, "speedBoostPhase": 0.75, "useTime": 400.0, "phaseRangeBoost": 20.0,
                           "hasBoost": True, "baseColor": "feb380ff", "phaseColor": "ffd59eff"},
    "OverflowDuct": {"extend": "Block", "speed": 5.0, "topRegion": None},
    "OverflowGate": {"extend": "Block", "speed": 1.0, "invert": False},

    "PayloadConveyor": {"extend": "Block", "moveTime": 45.0, "moveForce": 201.0, "topRegion": None, "edgeRegion": None,
                        "interp": "pow5", "payloadLimit": 3.0},
    "PayloadRouter": {"extend": "PayloadConveyor", "overRegion": None},

    "PowerDiode": {"extend": "Block", "arrow": None},
    "Prop": {"extend": "Block"},

    "Radar": {"extend": "Block", "discoveryTime": 600.0, "rotateSpeed": 2.0, "baseRegion": None, "glowRegion": None,
              "glowColor": "ab3400ff", "glowScl": 5.0, "glowMag": 0.6},
    "RegenProjector": {"extend": "Block", "range": 14, "healPercent": 0.2, "optionalMultiplier": 2.0,
                       "optionalUseTime": 480.0, "drawer": None, "effectChance": 0.03, "baseColor": "ffd37fff",
                       "effect": "regenParticle"},
    "RepairTower": {"extend": "Block", "range": 80.0, "circleColor": "98ffa9ff", "glowColor": "98ffa97f",
                    "circleSpeed": 120.0, "circleStroke": 3.0, "squareRad": 3.0, "squareSpinScl": 0.8, "glowMag": 0.5,
                    "glowScl": 8.0, "healAmount": 1.0, "glow": None},
    "RepairTurret": {"extend": "Block", "timerTarget": 1, "timerEffect": 2, "repairRadius": 50.0, "repairSpeed": 0.3,
                     "powerUse": 0.0, "length": 5.0, "beamWidth": 1.0, "pulseRadius": 6.0, "pulseStroke": 2.0,
                     "acceptCoolant": False, "coolantUse": 0.5, "coolEffect": "fuelburn", "coolantMultiplier": 1.0,
                     "baseRegion": None, "laser": None, "laserEnd": None, "laserTop": None, "laserTopEnd": None,
                     "laserColor": "98ffa9ff", "laserTopColor": "ffffffff"},

    "Router": {"extend": "Block", "speed": 8.0},

    "Prop": {"extend": "Block"},
    "Seaweed": {"extend": "Prop"},
    "SeaBush": {"extend": "Prop", "botRegion": None, "centerRegion": None, "lobesMin": 7, "lobesMax": 7,
                "botAngle": 60.0, "origin": 0.1, "sclMin": 30.0, "sclMax": 50.0, "magMin": 5.0, "magMax": 15.0,
                "timeRange": 40.0, "spread": 0.0},

    "Separator": {"extend": "Block", "results": None, "craftTime": 0.0, "liquidRegion": None, "spinnerRegion": None,
                  "spinnerSpeed": 3.0},
    "ShieldBreaker": {"extend": "Block", "toDestroy": [], "effect": "shockwave", "breakEffect": "reactorExplosion",
                      "selfKillEffect": "massiveExplosion"},
    # "ShockMine": {"extend": "Block", "timerDamage": 1, "cooldown": 80.0},

    # "genericsmelter": {"type": "GenericSmelter", "name": "Name", "description": "Description", "health": "120", "size": "1", "requirements": [{ "item": "lead", "amount": 2}], "hasPower": False, "hasItems": False, "hasLiquids": False, "craftTime": "3", "consumes": "{}", "updateEffect": "", "category": "crafting", "research": "cultivator", "alwaysUnlocked": False, "idleSoundVolume": 1.5, "itemCapacity": 30, "outputLiquid": {}},

    "Item": {"extend": "UnlockableContent", "color": "000000ff", "explosiveness": 0.0, "flammability": 0.0,
             "radioactivity": 0.0, "charge": 0.0, "hardness": 0, "cost": 1.0, "healthScaling": 0.0,
             "lowPriority": False, "frames": 0, "transitionFrames": 0, "frameTime": 5.0, "buildable": True,
             "hidden": False, "hiddenOnPlanets": None},
    "Material": {"extend": "Item"},

    "Liquid": {"extend": "UnlockableContent", "gas": False, "color": "000000ff", "gasColor": "bfbfbfff",
               "barColor": None, "lightColor": "00000000", "flammability": 0.0, "temperature": 0.5, "heatCapacity": 0.5,
               "viscosity": 0.5, "explosiveness": 0.0, "blockReactive": True, "coolant": True,
               "moveThroughBlocks": False, "incinerable": True, "effect": None, "particleEffect": None,
               "particleSpacing": 60.0, "boilPoint": 2.0, "capPuddles": True, "vaporEffect": "vapor", "hidden": False,
               "canStayOn": None},
    "CellLiquid": {"extend": "Liquid", "colorFrom": "ffffffff", "colorTo": "ffffffff", "cells": 8, "spreadTarget": None,
                   "maxSpread": 0.75, "spreadConversion": 1.2, "spreadDamage": 0.11, "removeScaling": 0.25},

    # "items": {
    #	"items": {"name": "Name", "description": "Description", "color": "000000ff", "explosiveness": 0.0, "fliammbility": 0.0, "radiioactivity": 0.0, "hardness": 0, "cost": 1.0, "healthScaling": 0.0, "lowPriority": False, "frames": 0, "transitionFrames": 0, "frameTime": 5.0, "buildable": True, "research": "copper", "alwaysUnlocked": False},

    #	"material": {"type": "Material", "name": "Name", "description": "Description", "color": "000000ff", "explosiveness": 0.0, "fliammbility": 0.0, "radiioactivity": 0.0, "hardness": 0, "cost": 1.0, "healthScaling": 0.0, "lowPriority": False, "frames": 0, "transitionFrames": 0, "frameTime": 5.0, "buildable": True, "research": "copper", "alwaysUnlocked": False},
    #	"resource": {"type": "Resource", "name": "Name", "description": "Description", "color": "000000ff", "explosiveness": 0.0, "fliammbility": 0.0, "radiioactivity": 0.0, "hardness": 0, "cost": 1.0, "healthScaling": 0.0, "lowPriority": False, "frames": 0, "transitionFrames": 0, "frameTime": 5.0, "buildable": True, "research": "copper", "alwaysUnlocked": False},
    # },

    # "liquids": {
    #	"liquids": {"name": "Name", "description": "Description", "color": "ffffff", "explosiveness": "0", "fliammbility": "0", "radioactivity": "0", "hardness": "1", "cost": "1", "viscosity": "0.55", "heatCapacity": "3", "effect": "freezing", "lightColor": "000000", "research": "copper", "alwaysUnlocked": False},

    #	"liquid": {"name": "Name", "description": "Description", "color": "ffffff", "explosiveness": "0", "fliammbility": "0", "radioactivity": "0", "hardness": "1", "cost": "1", "viscosity": "0.55", "heatCapacity": "3", "effect": "freezing", "lightColor": "000000", "research": "copper", "alwaysUnlocked": False},
    # }
}
}